spring:
  datasource:
    url: jdbc:mysql://i8c207.p.ssafy.io:3306/gaza?useSSL=false&useUnicode=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ssafy
    password: ssafy
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  main:
    allow-bean-definition-overriding: true
  jwt:
    accessSecret: gazagazagazagazagazagazagazagazagazagazagazagazagaza
    refreshSecret: zagazagazagazagazagazagazagazagazagazagazagazagazaga
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB

logging:
  pattern:
    file: "%-4relative [%thread] %-5level %logger{35} - %msg%n"
  file:
    name: ./log/logs.log
  level:
    root: info
    com.idle.gaza: Debug
redis:
  host: i8c207.p.ssafy.io
  port: 6379

cloud:
  aws:
    s3:
      bucket: ssafy.common.gaza
    credentials:
      access-key: AKIA5BFM4SWSVFF4CGKG
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    directory: /gaza

session:
  store-type:redis

OPENVIDU_URL: https://i8c207.p.ssafy.io:8443/
OPENVIDU_SECRET: GAZA
